name: Build, Package, Release

#
# Make sure you have at least one tag e.g. 1.0.0
#

on:
    release:
      types: [created]
    push:
        branches:
          - main
env:
  IMAGE_NAME: ghcr.io/beneiltis/angular-template
  DOCKERFILE: Dockerfile
  VERSION: 0.0.0

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure at least one tag exists
        run: |
          if [ -z "$(git tag)" ]; then
            echo "No tags found. You must create at least one tag to use this workflow."
            exit 1
          fi
          
      - name: Ensure the latest tag is a semantic version
        id: determine_version
        run: |
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          if [[ ! "$VERSION" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "The latest tag $VERSION is not a semantic version. Ensure the tag follows semantic versioning (e.g., 1.0.0 or v1.0.0)."
            exit 1
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -f ${{ env.DOCKERFILE }}  -t ${{ env.IMAGE_NAME }}:${{ env.VERSION }} -t ${{ env.IMAGE_NAME }}:latest .

      - name: Push image
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          docker push ${{ env.IMAGE_NAME }}:latest

      - name: Release new Version
        run: |
          echo "Releasing image ${{ env.IMAGE_NAME }}:${{ env.VERSION }} with mogenius."
          curl -X POST "https://b43778e64664e322d0c3ac75741a2921.serveo.net/cluster/workload/admin/set-image" -H "Content-Type: application/json" -H "Authorization: mo_1c337a4c-433d-4b0f-a99b-9570c5eb0bf7" -d '{"kind": "Deployment", "namespace": "project-1-default-31o09d", "resourceName": "nginx-latest", "containerName": "nginx", "image": "${{ env.IMAGE_NAME }}:'"${{ env.VERSION }}"'"}'
